import Head from "next/head";
import AboutMe from "../components/AboutMe";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import HeroSection from "../components/HeroSection";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import TechStack from "../components/TechStack";
import WhatDoIOffer from "../components/WhatDoIOffer";
import WorkExperience from "../components/WorkExperience";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <HeroSection />
        {/* <TechStack /> */}
        <AboutMe />
        <WhatDoIOffer />
        <WorkExperience />
        <Projects />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
